#pragma once
#include <cstring>
#include <cstdint>
#include <new>
#include <optional>
#include "any.h"
#include "string.h"
#include "datetime.h"
#include "array.h"
#include "object.h"
#include "struct.h"
#include "marshaler.h"
#include "default_value.h"
#include "methodptr.h"