cmake_minimum_required(VERSION 3.8)
if(NOT DEFINED EOC_BUILD_HELPER_INCLUDED)
	set(EOC_BUILD_HELPER_INCLUDED 1)
	
	if(NOT DEFINED EOC_HOME)
		set(EOC_HOME ${CMAKE_CURRENT_LIST_DIR})
	endif()
	set(EOC_LIBS_DIRS ${EOC_HOME}/lib)
	set(EOC_THIRD_PARTY_DIRS ${EOC_HOME}/3rd-party)
	set(CMAKE_USER_MAKE_RULES_OVERRIDE ${CMAKE_CURRENT_LIST_DIR}/c_flag_overrides.cmake)
	set(CMAKE_USER_MAKE_RULES_OVERRIDE_CXX ${CMAKE_CURRENT_LIST_DIR}/cxx_flag_overrides.cmake)

	list(APPEND CMAKE_PREFIX_PATH ${EOC_THIRD_PARTY_DIRS})
endif()